### ISSUE TITLE
Consider using 'Turtle' instead of 'bash'

### ISSUE THREAD

**Issue by ChShersh** [harendra-kumar/packcheck#2]
Since this script designed for Haskell packages, I find it more appropriate to implement whole logic using `Turtle` library.

* https://hackage.haskell.org/package/turtle

**Comment by harendra-kumar** [comment]
I was thinking of using turtle when I wrote this but I chose bash for deployment reasons, because of its universal availability on all platforms without going through the hoops. If I use Haskell I will either have to distribute/deploy a binary version of the script for each platform or have a requirement of having a working ghc compiler/ required packages installed on the machine. Since this is supposed to be CI script I chose bash for easier deployment. The script has been written mostly in functional manner though :-)
