### ISSUE TITLE
stack nightly builds fail because cabal-install has no build plan

### ISSUE THREAD

**Issue by sjakobi** [harendra-kumar/packcheck#7]
[Example](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/354140532#L652)

I'm not even quite sure why stack installs `cabal-install`?

In any case I don't think that the build tool needs to come from the same resolver as the dependencies. I think you could just take one from the PPA.

**Comment by harendra-kumar** [comment]
Thanks for reporting @sjakobi .

cabal is needed in stack builds in two cases:

* for `stack init --solver` when there is no `stack.yaml` in the project
* for `cabal info .` to show info from cabal file when building from source distribution. Let me know if you happen to know a way to display equivalent info without using cabal.

In your case it is the second one. Since this is only for displaying info we can avoid this. Let me commit a fix and you can upgrade to the new commit of packcheck in your config files. I have made a few more changes to the config files (not significant though) so you may want to upgrade to the new versions if you want. You can take a look at the changelog as well.

**Comment by harendra-kumar** [comment]
Yes, I think we can use it from PPA for this reason. I wanted to automate any installation as much as possible since we use packcheck on local machine as well. First of all we should not use the project stack.yaml to install cabal-install, second if the installation fails we can say that you should install cabal manually (i.e. specify the PPA in CI builds or use system package manager on local machines).

**Comment by harendra-kumar** [comment]
> In your case it is the second one. Since this is only for displaying info we can avoid this. 

sorry, this is not just for info. We need to retrieve the package version from the cabal file to unpack the sdist tar. So this is needed for sdist builds. We can use the PPA installed cabal though.

**Comment by harendra-kumar** [comment]
The only way I see to identify the sdist tar file generated by stack is by parsing:

```
Wrote sdist tarball to /vol/hosts/cueball/workspace/packages/packcheck/.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/packcheck-0.1.2.tar.gz
```

This is fragile (it will become even more difficult/fragile if the filename has spaces) but I can use it as long as it works. Is there any better way to either know the package version or the sdist file name without using cabal?

**Comment by harendra-kumar** [comment]
Another thing, on Mac OSX and on Windows I rely on stack to install `cabal-install`, I don't know how to install cabal binary package on these in a portable way. Let me know if you have any idea.

**Comment by harendra-kumar** [comment]
Ironically, even though stack and cabal do not seem to like each other very much I need stack for cabal build and cabal for stack build!

**Comment by harendra-kumar** [comment]
@sjakobi I fixed the problem. The code already had a workaround for this specific problem but it was not sufficient for CI machines. The current fix should work universally. You can enable your Mac OSX and Windows builds as well. Let me know if it does not work for you.

**Comment by sjakobi** [comment]
Thanks for looking into this @harendra-kumar!

Strangely [the problem persists](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/354481673) after I updated to the latest packcheck commit.

Maybe it would be possible to install `cabal-install` with `--resolver lts` instead of `nightly`.

**Comment by harendra-kumar** [comment]
Yes, I in fact added `--resolver lts` at one point when I was fixing this, but then I thought we should use the user specified resolver for everything. But it seems that won't work so well with nightlies.

**Comment by harendra-kumar** [comment]
@sjakobi fixed once again. Can you try now?

**Comment by sjakobi** [comment]
Works! Thank you! :+1:
