### ISSUE TITLE
Don't let stack reinstall cabal-install if it's already on the system

### ISSUE THREAD

**Issue by sjakobi** [harendra-kumar/packcheck#9]
I think that at least when the same or a newer cabal version is already present on the system, the reinstall should be avoided.

In [this case](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/355584876#L699), I had already installed cabal-install from hvr's PPA _and_ I think cabal-install should already have been cached in `~/.local/bin`.

**Comment by harendra-kumar** [comment]
You need to have `CABALVER` and `GHCVER` variables specified in the env for cabal and ghc to be picked up from the PATH:

```
  - env: BUILD=stack RESOLVER=nightly
    addons: {apt: {packages: [cabal-install-2.2], sources: [hvr-ghc]}}
```

Maybe I can put a message in the logs saying that we are installing cabal because CABALVER envvar was not specified.

**Comment by harendra-kumar** [comment]
BTW, there is not automatic way to figure this out without an envvar. In fact the binaries are placed in the PATH from the shell script in the travis config file by looking at these vars. See at the bottom of the travis file.

**Comment by sjakobi** [comment]
> You need to have CABALVER and GHCVER variables specified in the env for cabal and ghc to be picked up from the PATH:

Thanks for the hint! :)

> Maybe I can put a message in the logs saying that we are installing cabal because CABALVER envvar was not specified.

That sounds like a good idea to me.

**Comment by harendra-kumar** [comment]
I pushed a commit, now the situation is much better. CABALVER and GHCVER are not needed if you specify the correct cabal/ghc in apt-sources. So your original config that you used when filing this bug should work now. You can give it a try. 

See the new .travis.yml in packcheck repo, it is simpler now. The GHCVER envvar is now used only for documentation for the test, otherwise just apt-sources are enough.

**Comment by sjakobi** [comment]
Cheers! :)
